name: Slither Analysis

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@dev-git-safe-workspace
        id: slither
        with:
          sarif: results.sarif
          node-version: 16
          target: ./contracts
          fail-on: none

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: github.repository == 'SpecularL2/specular'
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

